### ISSUE TITLE
Loading custom VCF files

### ISSUE THREAD

**Issue by mamtagiri** [broadinstitute/gnomad-browser#567]
HI Guys,

We have a huge dataset that we generated VCF on. This has more of a disease (one disorder) and control set. Is there a way I can upload this dataset on the local instance of gnomad that I have installed?

Also, is it possible to visualize p value and fold change as well?

What might be the best way to move forward with this. If there is any reference please point me to it.

Thanks a bunch!!
Mamta

**Comment by nawatts** [comment]
Hi @mamtagiri,

Unfortunately there's no really easy way to do this. It will require changes to code in a few places.

We use [Hail](https://hail.is/docs/0.2/index.html) to load data into [Elasticsearch](https://www.elastic.co/elasticsearch/). Those scripts can be found in the [data](https://github.com/broadinstitute/gnomad-browser/tree/master/data) folder.

The browser has a concept of different "datasets" than be displayed (gnomAD v2, its subsets, and gnomAD v3). You could load your data into Elasticsearch or some other database and implement functions to fetch variants for a gene/region/transcript similar to the existing datasets ([gnomAD v2](https://github.com/broadinstitute/gnomad-browser/tree/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad-api/src/schema/datasets/gnomad_r2_1), [gnomAD v3](https://github.com/broadinstitute/gnomad-browser/tree/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad-api/src/schema/datasets/gnomad_r3)) and add them to [datasetsConfig.js](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad-api/src/schema/datasets/datasetsConfig.js).

However, currently the gene/region/transcript pages assume all datasets return the same type of data for variants (defined by [this GraphQL type](https://github.com/broadinstitute/gnomad-browser/blob/13500541001a0b1a73841818cc8b3c01d7ceb5e5/projects/gnomad-api/src/schema/types/variant.js#L39-L65)). So if your variant data has a different format, then it might be better to add another field similar to the existing `variants` on the [gene](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad-api/src/schema/types/gene.js#L206-L232)/[region](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad-api/src/schema/types/region.js#L117-L141)/[transcript](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad-api/src/schema/types/transcript.js#L140-L166) types.

On the user interface side, you could modify the GraphQL queries for the [gene](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad/src/client/GenePage/VariantsInGene.js#L254-L310)/[region](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad/src/client/RegionPage/VariantsInRegion.js#L240-L297)/[transcript](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad/src/client/TranscriptPage/VariantsInTranscript.js#L246-L301) pages to fetch your data and modify [variantTableColumns.js](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad/src/client/VariantList/variantTableColumns.js) based on your variant fields.

**Comment by mamtagiri** [comment]
Great! Thats no problem as long as there is a way to add these onto the browser someway. Thanks for these suggestions. I will try making changes to the parts in the script pointed here.

Mamta

**Comment by mamtagiri** [comment]
HI Nick,

Another quick question. Once I load the custom VCF to the elastic server, do I need to do anything with the default dataset onto gnomad. Does the script overwrite that as the default dataset or the code needs to be changed to only load the custom data and not the fault gnomad dataset.

Thanks,
Mamta

**Comment by nawatts** [comment]
The existing GraphQL queries pass a `datasetId` parameter to the `variants` field (for example, the [gene page query](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad/src/client/GenePage/VariantsInGene.js#L265)), which determines which dataset (gnomAD v2, v3, etc.) is shown.

That `datasetId` parameter is passed down from the Route components in [routes.js](https://github.com/broadinstitute/gnomad-browser/blob/5b87de7a50488e03fafd18c65970fbc7d45973b5/projects/gnomad/src/client/routes.js), which take it from the `dataset` query parameter, if it exists. If no `dataset` query parameter is provided, then a default dataset (defined in [routes.js](https://github.com/broadinstitute/gnomad-browser/blob/5b87de7a50488e03fafd18c65970fbc7d45973b5/projects/gnomad/src/client/routes.js#L31)) is used. If you have modified or replaced those GraphQL queries, you may or may not need to do anything with that `datasetId`.

On the data loading / Elasticsearch side, `export_hail_table_to_elasticsearch.py` requires you to [specify an index to use](https://github.com/broadinstitute/gnomad-browser/blob/5b87de7a50488e03fafd18c65970fbc7d45973b5/data/export_hail_table_to_elasticsearch.py#L13). If an existing index is specified, then it will be overwritten. The index names for gnomAD data are defined in the resolver functions for variant fields (for example, [fetchGnomadVariantDetails](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad-api/src/schema/datasets/gnomad_r2_1/fetchGnomadVariantDetails.js#L157-L161)).

**Comment by mamtagiri** [comment]
thanks!

**Comment by mamtagiri** [comment]
HI Nick-

Any suggestion on how to create the coverage file compatible for gnomad?
Thanks,
mamta

**Comment by nawatts** [comment]
The coverage files need chromosome and position and then whatever coverage metrics you want to display (for gnomAD, we have mean and median coverage and fraction over a series of thresholds).

There are scripts to format data files. See the [ExAC script](https://github.com/broadinstitute/gnomad-browser/blob/772d4a51bffaf79ec6630fa5e30b0417bb22b8aa/data/exac/prepare_exac_coverage.py) for an example using TSVs and the [gnomAD script](https://github.com/broadinstitute/gnomad-browser/blob/772d4a51bffaf79ec6630fa5e30b0417bb22b8aa/data/gnomad_r2_1/prepare_gnomad_r2_1_coverage.py) for an example using a Hail Table. The Elasticsearch queries for coverage are in [`projects/gnomad-api/src/schema/types/coverage.js`](https://github.com/broadinstitute/gnomad-browser/blob/772d4a51bffaf79ec6630fa5e30b0417bb22b8aa/projects/gnomad-api/src/schema/types/coverage.js). Those could be modified to add or remove metrics.

**Comment by mamtagiri** [comment]
thanks! those scripts are exactly what I needed.

I installed elasticsearch-7.6.2 on Ubuntu 18.04.4 and that runs ok. Will the load data to Elasticsearch server be the same as described for upload to the cluster?

**Comment by nawatts** [comment]
Hail's [export_elasticsearch](https://hail.is/docs/0.2/methods/impex.html#hail.methods.export_elasticsearch) function uses the [Elasticsearch for Hadoop](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html) connector. If not running the export scripts in a Hadoop environment, you may need to use Elasticsearch's [bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) to load data instead.

**Comment by mamtagiri** [comment]
Thanks Nick,

I looked at the bulk API. I have converted my vcf to a hail table format (a folder with multiple files). Not sure if I can use this with PUT. Sorry if its a very naive question. Do I have to convert it to any other format? Or do I have to define index for every entry?

**Comment by mamtagiri** [comment]
nvm. I skipped the prepare variants steps. will try that and then deal with the output.

**Comment by mamtagiri** [comment]
Hey!

For the prepare_gnomad_r2_1_variants.py  scripts. I somehow get error related to module data_utils. Also when I look at the folder, I dont see import normalized_contig, x_position under the folder. How do I get that?

>>> from data_utils.computed_fields import normalized_contig, variant_id, x_position, sorted_transcript_consequences_v2

**Comment by nawatts** [comment]
The `data_utils` package is in [`gnomad-browser/data/data_utils`](https://github.com/broadinstitute/gnomad-browser/tree/master/data/data_utils). When using those scripts on a Dataproc cluster, they are submitted with `hailctl dataproc submit cluster  --pyfiles ./data/data_utils ./path/to/script.py`, which adds `data_utils` to Python's import path. When running locally, try
```
PYTHONPATH=$PYTHONPATH:/path/to/gnomad-browser/data python script.py
```

To use the Elasticsearch Bulk API instead of Hail's `export_elasticsearch`, try replacing `hl.export_elasticsearch` in `data/data_utils/elasticsearch_export.py`.
https://github.com/broadinstitute/gnomad-browser/blob/772d4a51bffaf79ec6630fa5e30b0417bb22b8aa/data/data_utils/elasticsearch_export.py#L115
with
```python
from elasticsearch import helpers

temp_file = "table-tmp.json.txt"
table = table.key_by()
table.select(json=hl.json(table.row_value)).export(temp_file, header=False)

buffer = []
with open(temp_file) as f:
    for line in f:
        data = json.loads(line)
        buffer.append(data)

        if len(buffer) >= block_size:
            helpers.bulk(
                es_client,
                build_bulk_request(buffer, index_name, type_name, id_field)
            )
            buffer = []

if buffer:
    helpers.bulk(
        es_client,
        build_bulk_request(buffer, index_name, type_name, id_field)
    )
    buffer = []
```

**Comment by mamtagiri** [comment]
thanks so much Nick!

However, gnomad-browser/data/data_utils/computed_fields is missing **normalized_contig** and **x_position** which prepare_gnomad_r2_1_variants.py tries to import.

Is there any other location that I can get those 2 files from?

**Comment by nawatts** [comment]
Those two functions are in [`data/data_utils/computed_fields/variant_id.py`](https://github.com/broadinstitute/gnomad-browser/blob/772d4a51bffaf79ec6630fa5e30b0417bb22b8aa/data/data_utils/computed_fields/variant_id.py)

**Comment by mamtagiri** [comment]
great- thanks!

**Comment by mamtagiri** [comment]
I tried this on my vcf (converted to hail table) as well as on the downloaded ht sites file from the googlecloud.

However it keeps giving me the error:

(hail) mamta@avi:~/Test$ PYTHONPATH=$PYTHONPATH:/home/mamta/Test/gnomad-browser/data python prepare_gnomad_r2_1_variants.py /home/mamta/vcf/gnomad.exomes.r2.1.1.sites.ht  mydata
  File "prepare_gnomad_r2_1_variants.py", line 85
    AC_raw=ds.freq[g.freq_index_dict[f"{subset}_raw"]].AC,
                                                   ^
SyntaxError: invalid syntax

I tried to debug in Jupyter notebook.. it seemed first that variant_id was the issue but once I resolved that I got Nonetype error. 

Is this a python version issue? Iam using 3.6.9. 
Does this run OK with the gnomad.exomes.r2.1.1.sites.ht data?

Thanks!

**Comment by mamtagiri** [comment]
> The `data_utils` package is in [`gnomad-browser/data/data_utils`](https://github.com/broadinstitute/gnomad-browser/tree/master/data/data_utils). When using those scripts on a Dataproc cluster, they are submitted with `hailctl dataproc submit cluster --pyfiles ./data/data_utils ./path/to/script.py`, which adds `data_utils` to Python's import path. When running locally, try
> 
> ```
> PYTHONPATH=$PYTHONPATH:/path/to/gnomad-browser/data python script.py
> ```
> 
> To use the Elasticsearch Bulk API instead of Hail's `export_elasticsearch`, try replacing `hl.export_elasticsearch` in `data/data_utils/elasticsearch_export.py`.
> 
> https://github.com/broadinstitute/gnomad-browser/blob/772d4a51bffaf79ec6630fa5e30b0417bb22b8aa/data/data_utils/elasticsearch_export.py#L115
> 
> 
> with
> ```python
> from elasticsearch import helpers
> 
> temp_file = "table-tmp.json.txt"
> table = table.key_by()
> table.select(json=hl.json(table.row_value)).export(temp_file, header=False)
> 
> buffer = []
> with open(temp_file) as f:
>     for line in f:
>         data = json.loads(line)
>         buffer.append(data)
> 
>         if len(buffer) >= block_size:
>             helpers.bulk(
>                 es_client,
>                 build_bulk_request(buffer, index_name, type_name, id_field)
>             )
>             buffer = []
> 
> if buffer:
>     helpers.bulk(
>         es_client,
>         build_bulk_request(buffer, index_name, type_name, id_field)
>     )
>     buffer = []
> ```


Hi Nick,

I replaced the part above in elasticsearch_export.py. It finishes pretty soon (which is suspicious) and also when I look at my indices I dont see anything added for this one. Since I don't see any error its hard to debug. Any suggestion on what might be going on wrong or what I should check?

Thanks!!

**Comment by nawatts** [comment]
> It finishes pretty soon (which is suspicious)

Was this running `data/data_utils/elasticsearch_export.py` or `data/export_hail_table_to_elasticsearch.py`? The first only defines a function, the second provides a command line interface to call that function.

(Looking at it now, those files should probably be combined. They are separate because there used to be multiple scripts that imported `data_utils.elasticsearch_export`).

**Comment by nawatts** [comment]
> ```python
> from elasticsearch import helpers
> 
> temp_file = "table-tmp.json.txt"
> table = table.key_by()
> table.select(json=hl.json(table.row_value)).export(temp_file, header=False)
> 
> buffer = []
> with open(temp_file) as f:
>     for line in f:
>         data = json.loads(line)
>         buffer.append(data)
> 
>         if len(buffer) >= block_size:
>             helpers.bulk(
>                 es_client,
>                 build_bulk_request(buffer, index_name, type_name, id_field)
>             )
>             buffer = []
> 
> if buffer:
>     helpers.bulk(
>         es_client,
>         build_bulk_request(buffer, index_name, type_name, id_field)
>     )
>     buffer = []
> ```

Oops, looks like I forgot to include the definition for `build_bulk_request` in this code.

```python
def build_bulk_request(documents, index_name, type_name, id_field=None):
    if id_field:
        return [{"_index": index_name, "_type": type_name, "_id": d[id_field], "_source": d} for d in documents]
    else:
        return [{"_index": index_name, "_type": type_name, "_source": d} for d in documents]
```

**Comment by mamtagiri** [comment]
> > It finishes pretty soon (which is suspicious)
> 
> Was this running `data/data_utils/elasticsearch_export.py` or `data/export_hail_table_to_elasticsearch.py`? The first only defines a function, the second provides a command line interface to call that function.
> 
> (Looking at it now, those files should probably be combined. They are separate because there used to be multiple scripts that imported `data_utils.elasticsearch_export`).

yes, that was only using elasticsearch_export.py.
But we replaced hl.export_elasticsearch in the above script? We still combine export_hail_table_to_elasticsearch.py with elasticsearch_export.py?

**Comment by mamtagiri** [comment]
> ```python
> ```python
> from elasticsearch import helpers
> 
> temp_file = "table-tmp.json.txt"
> table = table.key_by()
> table.select(json=hl.json(table.row_value)).export(temp_file, header=False)
> 
> buffer = []
> with open(temp_file) as f:
>     for line in f:
>         data = json.loads(line)
>         buffer.append(data)
> 
>         if len(buffer) >= block_size:
>             helpers.bulk(
>                 es_client,
>                 build_bulk_request(buffer, index_name, type_name, id_field)
>             )
>             buffer = []
> 
> if buffer:
>     helpers.bulk(
>         es_client,
>         build_bulk_request(buffer, index_name, type_name, id_field)
>     )
>     buffer = []
> ```
> 
> 
> 
> Oops, looks like I forgot to include the definition for build_bulk_request in this code.
> ```python
> def build_bulk_request(documents, index_name, type_name, id_field=None):
>     if id_field:
>         return [{"_index": index_name, "_type": type_name, "_id": d[id_field], "_source": d} for d in documents]
>     else:
>         return [{"_index": index_name, "_type": type_name, "_source": d} for d in documents]
> ```
> ```

thanks! Will try adding this to the script.

Mamta

**Comment by nawatts** [comment]
> yes, that was only using elasticsearch_export.py.
But we replaced hl.export_elasticsearch in the above script? We still combine export_hail_table_to_elasticsearch.py with elasticsearch_export.py?

Yes. [`hl.export_elasticsearch`](https://hail.is/docs/0.2/methods/impex.html?highlight=export_elasticsearch#hail.methods.export_elasticsearch) is replaced by Elasticsearch's Bulk API for uploading the data to ES, but the other parts of `data/data_utils/elasticsearch_export.py` are still useful (creating the index and defining a mapping based on the Hail Table's schema).

**Comment by mamtagiri** [comment]
I get a series of errors: I am now trying to understand if I did anything wrong here.

<img width="1440" alt="Errors_EXPORTtoElasticSearch" src="https://user-images.githubusercontent.com/44902002/80825758-03f2c180-8baf-11ea-9fd6-4af93334f713.png">

**Comment by nawatts** [comment]
That error looks like it's caused by the globals structure in the Hail Table.

The gnomAD variants tables have some global values that the function in `elasticsearch_export.py` doesn't know how to serialize to JSON.

Removing either of these lines should resolve it (the table's global values won't be stored in Elasticsearch, but nothing in the browser requires that they are).
https://github.com/broadinstitute/gnomad-browser/blob/f02dfe0477da46651b9b98b4d3218ea57d250eab/data/export_hail_table_to_elasticsearch.py#L37

https://github.com/broadinstitute/gnomad-browser/blob/f02dfe0477da46651b9b98b4d3218ea57d250eab/data/data_utils/elasticsearch_export.py#L94

**Comment by mamtagiri** [comment]
thanks that actually solved that error.

However, I get another error now.
<img width="1424" alt="Screen Shot 2020-05-01 at 1 47 07 PM" src="https://user-images.githubusercontent.com/44902002/80827894-7022f480-8bb2-11ea-9fc7-aabbeeaffd52.png">


I really appreciate your time. I couldn't have solved these without the help. Sorry about the multiple of these.
Thanks!

**Comment by nawatts** [comment]
Looks like this is due to changes in Elasticsearch 7. So far, these scripts have only been tried with ES 5.

https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#breaking_70_mappings_changes

I was able to get it to work with ES 7 with the following changes:
* Remove `mapping["_all"] = {"enabled": "false"}` line
* Change `"mappings": {type_name: mapping}` to `"mappings": mapping` in `request_body`
* Remove `_type` from dicts in `build_bulk_request`

**Comment by mamtagiri** [comment]
I see. I was also in the comments. sorry didn't notice it before.

I ran again with the suggestion but still face errors, unfortunately :(

<img width="1052" alt="Screen Shot 2020-05-01 at 2 47 54 PM" src="https://user-images.githubusercontent.com/44902002/80832551-db70c480-8bba-11ea-987e-e11a2481b4d6.png">

**Comment by nawatts** [comment]
> `Root mapping definition has unsupported parameters: [documents: {_meta=...`

"documents" in that error message suggests that the `request_body` variable for creating the index still has `"mappings": {type_name: mapping}`. That needs to be changed to `"mappings": mapping`.

```python
import argparse
import datetime
import json

import elasticsearch
from elasticsearch import helpers
import hail as hl


HAIL_TYPE_TO_ES_TYPE_MAPPING = {
    hl.tint: "integer",
    hl.tint32: "integer",
    hl.tint64: "long",
    hl.tfloat: "double",
    hl.tfloat32: "float",
    hl.tfloat64: "double",
    hl.tstr: "keyword",
    hl.tbool: "boolean",
}


# https://hail.is/docs/devel/types.html
# https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html
def _elasticsearch_mapping_for_hail_type(dtype):
    if isinstance(dtype, hl.tstruct):
        return {"properties": {field: _elasticsearch_mapping_for_hail_type(dtype[field]) for field in dtype.fields}}

    if isinstance(dtype, (hl.tarray, hl.tset)):
        element_mapping = _elasticsearch_mapping_for_hail_type(dtype.element_type)

        if isinstance(dtype.element_type, hl.tstruct):
            element_mapping["type"] = "nested"

        return element_mapping

    if isinstance(dtype, hl.tlocus):
        return {"type": "object", "properties": {"contig": {"type": "keyword"}, "position": {"type": "integer"}}}

    if dtype in HAIL_TYPE_TO_ES_TYPE_MAPPING:
        return {"type": HAIL_TYPE_TO_ES_TYPE_MAPPING[dtype]}

    # tdict, ttuple, tinterval, tcall
    raise NotImplementedError


def _set_field_parameter(mapping, field, parameter, value):
    keys = field.split(".")
    ref = mapping
    for key in keys:
        ref = ref["properties"][key]

    ref[parameter] = value


def elasticsearch_mapping_for_table(table, disable_fields=None, override_types=None):
    """
    Creates an Elasticsearch mapping definition for a Hail table's row value type.

    https://www.elastic.co/guide/en/elasticsearch/guide/current/root-object.html
    """
    mapping = _elasticsearch_mapping_for_hail_type(table.key_by().row_value.dtype)

    if disable_fields:
        for field in disable_fields:
            _set_field_parameter(mapping, field, "enabled", False)

    if override_types:
        for field, field_type in override_types.items():
            _set_field_parameter(mapping, field, "type", field_type)

    return mapping


def build_bulk_request(documents, index_name, id_field=None):
    if id_field:
        return [{"_index": index_name, "_id": d[id_field], "_source": d} for d in documents]
    else:
        return [{"_index": index_name, "_source": d} for d in documents]


def export_table_to_elasticsearch(
    table, host, index_name, block_size=5000, id_field=None, mapping=None, num_shards=10, port=9200, verbose=True
):
    es_client = elasticsearch.Elasticsearch(host, port=port)

    if not mapping:
        mapping = elasticsearch_mapping_for_table(table)

    # Delete the index before creating it
    if es_client.indices.exists(index=index_name):
        es_client.indices.delete(index=index_name)

    mapping["_meta"] = dict(hl.eval(table.globals))

    # https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-modules-settings
    request_body = {
        "mappings": mapping,
        "settings": {
            "index.codec": "best_compression",
            "index.mapping.total_fields.limit": 10000,
            "index.number_of_replicas": 0,
            "index.number_of_shards": num_shards,
            "index.refresh_interval": -1,
        },
    }

    es_client.indices.create(index=index_name, body=request_body)

    temp_file = "table-tmp.json.txt"
    table = table.key_by()
    table.select(json=hl.json(table.row_value)).export(temp_file, header=False)

    buffer = []
    with open(temp_file) as f:
        for line in f:
            data = json.loads(line)
            buffer.append(data)

            if len(buffer) >= block_size:
                helpers.bulk(
                    es_client,
                    build_bulk_request(buffer, index_name, id_field)
                )
                buffer = []

    if buffer:
        helpers.bulk(
            es_client,
            build_bulk_request(buffer, index_name, id_field)
        )
        buffer = []

    es_client.indices.forcemerge(index=index_name)



def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("table_url", help="URL of Hail table to export")
    parser.add_argument("host", help="Elasticsearch host or IP")
    parser.add_argument("index_name", help="Elasticsearch index name")
    parser.add_argument("--block-size", help="Elasticsearch block size to use when exporting", default=200, type=int)
    parser.add_argument("--disable-fields", help="Disable a field in Elasticsearch", action="append", default=[])
    parser.add_argument("--id-field", help="Field to use as Elasticsearch document ID", default=None)
    parser.add_argument("--num-shards", help="Number of elasticsearch shards", default=1, type=int)
    parser.add_argument("--port", help="Elasticsearch port", default=9200, type=int)
    parser.add_argument("--set-type", help="Set a specific Elasticsearch type for a field", action="append", default=[])
    args = parser.parse_args()

    hl.init(log="/tmp/hail.log")

    table = hl.read_table(args.table_url)

    table = table.select_globals(
        exported_from=args.table_url,
        exported_at=datetime.datetime.utcnow().isoformat(timespec="seconds"),
    )

    mapping = elasticsearch_mapping_for_table(
        table, disable_fields=args.disable_fields, override_types=dict(arg.split("=") for arg in args.set_type)
    )

    export_table_to_elasticsearch(
        table,
        host=args.host,
        index_name=args.index_name,
        block_size=args.block_size,
        id_field=args.id_field,
        mapping=mapping,
        num_shards=args.num_shards,
        port=args.port,
        verbose=True,
    )


if __name__ == "__main__":
    main()
```

**Comment by mamtagiri** [comment]
Awesome! that resolves the error.

Where does the tmp file get stored? Iam getting a no space on disk while writing hail table.

**Comment by mamtagiri** [comment]
Thanks Nick. This worked great.

I am starting to modify the script based on the new index created. Following are the scripts I am starting with. Please add if there is anything else that will depend on 1. the dataset loaded or 2. on type and display of variants.

1. Modify GraphQL for the datasetID parameter and datasetsConfig.js. (route.js only to change ?default dataset )

2. For the type of variant to call ( GraphQL , gene/region/transcript types ) and show (variantTableColumns.js)

**Comment by nawatts** [comment]
Excellent!

The [variant page components](https://github.com/broadinstitute/gnomad-browser/tree/f02dfe0477da46651b9b98b4d3218ea57d250eab/projects/gnomad/src/client/VariantPage) are also dependent on the shape of the variant objects. So is the code for [sorting](https://github.com/broadinstitute/gnomad-browser/blob/f02dfe0477da46651b9b98b4d3218ea57d250eab/projects/gnomad/src/client/VariantList/sortVariants.js) and [filtering](https://github.com/broadinstitute/gnomad-browser/blob/f02dfe0477da46651b9b98b4d3218ea57d250eab/projects/gnomad/src/client/VariantList/filterVariants.js) the variant lists on the gene/region/transcript pages.

**Comment by mamtagiri** [comment]
Ok. Thanks!

**Comment by mamtagiri** [comment]
HI Nick,

I am now working with a newer VCF that comes from genotyping data and hence doesn't have all of columns/fieldnames as a standard sequencing vcf.

in the pipeline -> vcf to hail (this shouldn't be a problem) -> vcf through _prepare_gnomad_r2_1_variants.py_ (this script will change , correct)
as well as _elasticsearch_exportUPDATED.py_ depending on the columns I have here? 

Is there a best way you suggest to find parts from this script that will need to be. modified?

Thanks!!

**Comment by nawatts** [comment]
The Elasticsearch export script should be mostly agnostic to the table schema.

The data preparation scripts, on the other hand, are all tightly connected to the gnomAD tables' schemas. They probably have to be almost entirely rewritten for a different dataset. There are a few pieces that could be reused, like the [variant ID fields](https://github.com/broadinstitute/gnomad-browser/blob/370e5d8/data/data_utils/computed_fields/variant_id.py).

**Comment by mamtagiri** [comment]
I see. thanks! Yea that makes sense. I was more of thinking of directly exporting the table (with limited columns) to elastic search and then modify the querying and viewing part from the scripts you describe in the first comment.

Please let me know if you think this for any reason might not work.

Thanks Nick.

Mamta

**Comment by mamtagiri** [comment]
HI Nick,

I could change most parts that I needed to modify in the scripts. 

I would however, like to change the display of **coverage metrics** to a different file (association plots like Manhattan). what scripts should I be looking at in order to change the data used as well as the graph plotted?
Thanks so much!
Mamta

**Comment by nawatts** [comment]
To add associations data, you would need to add fields and resolvers for that data to the GraphQL schema, probably to one or more of the [gene](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad-api/src/schema/types/gene.js), [region](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad-api/src/schema/types/region.js), [transcript](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad-api/src/schema/types/transcript.js), or [root](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad-api/src/schema/index.js) types and update the GraphQL queries on the [gene](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/GenePage/GenePageContainer.js#L12-L209)/[region](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/RegionPage/RegionPageContainer.js#L16-L36)/[transcript](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/TranscriptPage/TranscriptPageContainer.js#L12-L223) pages accordingly.

For the plots, replace the CoverageTrack components on the [gene](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/GenePage/GenePage.js#L310-L324)/[region](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/RegionPage/RegionPage.js#L83-L91)/[transcript](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/TranscriptPage/TranscriptPage.js#L323-L327) pages with a component to show the associations data. There is a Manhattan plot component in [packages/manhattan-plot](https://github.com/broadinstitute/gnomad-browser/tree/62f531f9839bf09a70041a57adda6255d3442c4c/packages/manhattan-plot).

**Comment by mamtagiri** [comment]
perfect thanks.

Also, on the variant page https://gnomad.broadinstitute.org/variant/1-55516888-G-GA
Where are the metrics being pulled from - is it the indexed data? (may I know what scripts do these pulls and visualization?)

I am planning to remove "Read Data" part of the browser in my local version. Not using it but curious from where are the bars files being pulled?

Thanks so much!

**Comment by nawatts** [comment]
For the variant page, the starting points are:
* [projects/gnomad/src/client/VariantPage/GnomadVariantPage.js](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/VariantPage/GnomadVariantPage.js)
* [projects/gnomad/src/client/VariantPage/queries/gnomadVariantQuery.js](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/VariantPage/queries/gnomadVariantQuery.js)
* [projects/gnomad-api/src/schema/index.js lines 144-159](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad-api/src/schema/index.js#L144-L159)
* [projects/gnomad-api/src/schema/datasets/gnomad_r2_1/fetchGnomadVariantDetails.js](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad-api/src/schema/datasets/gnomad_r2_1/fetchGnomadVariantDetails.js)

Read data for the IGV.js visualization is fetched separately from other variant data by the [GnomadReadData component](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/VariantPage/reads/GnomadReadData.js).

**Comment by mamtagiri** [comment]
Thanks Nick.

I am trying to modify the coverage data first before using the association data to plot. 
However, I can't figure out the way to change the graph type. Is there a way I can make it a dot/bar/Manhattanplot with the coverage data itself.

[gene](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/GenePage/GenePage.js#L310-L324) gives me the coverage track but in [GeneCoverageTrack](https://github.com/broadinstitute/gnomad-browser/blob/62f531f9839bf09a70041a57adda6255d3442c4c/projects/gnomad/src/client/GenePage/GeneCoverageTrack.js) Iam not sure how to modify the type of graph.

**Comment by mamtagiri** [comment]
Thanks Nick.

If my files are hg38 - I can still just replace V3 with my index and the other fetching and displaying scripts, right?
The only database/information I see I lose with this is GTEx. Is that right? 

I can also use hg19 if there can be any other issues with any other databases?

Mamta

**Comment by nawatts** [comment]
The two datasets without hg38 versions in gnomAD are GTEx and pext (which is based on GTEx).

There is an hg38 GTEx dataset (GTEx v8). We do not use it in gnomAD because it is based on a different version of Gencode (26) than other gnomAD data (29).

**Comment by mamtagiri** [comment]
> The Elasticsearch export script should be mostly agnostic to the table schema.
> 
> The data preparation scripts, on the other hand, are all tightly connected to the gnomAD tables' schemas. They probably have to be almost entirely rewritten for a different dataset. There are a few pieces that could be reused, like the [variant ID fields](https://github.com/broadinstitute/gnomad-browser/blob/370e5d8/data/data_utils/computed_fields/variant_id.py).

Hey Nick, I used the export script to export a hail table (created from a tab delimited file with id used as Variant_id), it ran for sometime but I dont see any index created for that. Is there a way I can check if it had any errors. Looked at the hail log file but couldn't figure out what might be wrong.

` sudo PYTHONPATH=$PYTHONPATH:/home/mamta/gnomad-browser/data nohup python3 /home/mamta/elasticsearch_exportUPDATED.py /home/mamta/vcf/EUR/EUR10k.ht http://localhost:9200 EUR_10k --id-field Variant_id
nohup: ignoring input and appending output to 'nohup.out'`

**Comment by nawatts** [comment]
I would expect an exception to be raised if something went wrong.

Depending on the size of the Hail table, this could take some time.
```
temp_file = "table-tmp.json.txt"
table = table.key_by()
table.select(json=hl.json(table.row_value)).export(temp_file, header=False)
```

Also, [tqdm](https://pypi.org/project/tqdm/) could be useful for showing progress in this part of the script.
```
buffer = []
with open(temp_file) as f:
    for line in f:
        data = json.loads(line)
```

**Comment by mamtagiri** [comment]
Thanks!The temp table was not written at all. 

Will the script work for any hail table or does it require certain fields/format?
My hail table is just a table with variants and its associated columns.

**Comment by nawatts** [comment]
It should work for any Hail table, it doesn't make assumptions about the row schema. However, some field types (dicts, tuples, intervals, calls) aren't handled by the `elasticsearch_mapping_for_table` function as is in https://github.com/broadinstitute/gnomad-browser/issues/567#issuecomment-622520187. For those, it will throw a NotImplementedError.

**Comment by mamtagiri** [comment]
Thanks for the quick reply .
Hmm.. I do not have those field types. 
Row fields:
    'CHR': str 
    'SNP': str 
    'BP': str 
    'A1': str 
    'A2': str 
    'FRQ_A_5956': str 
    'FRQ_U_14927': str 
    'INFO': str 
    'OR': str 
    'SE': str 
    'P': str 
    'Direction': str 
    'HetISqt': str 
    'HetPVa': str 
    'nstudies': str 
    'studies_included': str 
    'Variant_id': str 
Trying to figure what might be wrong.

**Comment by nawatts** [comment]
Errors from GraphQL should be available in the "errors" field of the API response and/or in console logs from your API server.

For development, it might also be helpful to remove the error formatting function [here](https://github.com/broadinstitute/gnomad-browser/blob/d5455777c54edf94829430bdd8b76876522cd499/projects/gnomad-api/src/server.js#L149-L174) and allow all error messages to be sent to the frontend.

**Comment by mamtagiri** [comment]
I ran removing the error formatting function. But I still dont see any error. Even the console doesn't show any error [just the frontend has failed to load variants]

This happens as I add an extra variable under [VariantsInGene](https://github.com/broadinstitute/gnomad-browser/blob/7bea5ae9c0082eb52088235a11aab11ed7135168/projects/gnomad/src/client/GenePage/VariantsInGene.js#L266)

**Comment by nawatts** [comment]
Sounds like possibly a query validation error. There's likely a message in the "errors" field of the API response.

It may be helpful to debug queries using the GraphiQL tool instead of the browser. By default, the start script in projects/gnomad-api runs the API on port 8007, so GraphiQL should be available at http://localhost:8007/api.

**Comment by mamtagiri** [comment]
this seems helpful. I can start the GraphiQL query tool now. Learning to debug now.

Mamta

**Comment by mamtagiri** [comment]
hmm... I not too familiar with GraphiQL, so its being a little difficult.
May I ask you to verify (if its not too much to ask for) my way of adding a new column in the Variant Table [column from the rowfields, not nested]. If this is not a quick answer then I will dig deeper into the scripts and the query.

1. FetchGnomadVariantsDetails.js
2. GnomadVariantsDetailsType.js
3. variant.js
4. FetchGnomadVariantsByGene.js
5. shapeGnomadVariantSummary.js
6. GnomadVariantquery.js
7.  VariantsInGene.js
8. variantTableColumns.js

**Comment by mamtagiri** [comment]
also, I named my index file gnomad_exomes_2_1_1 but I still see the original gnomad data. I was under the impression that it gets replaced.

Thanks,
Mamta

**Comment by nawatts** [comment]
fetchGnomadVariantsDetails.js, GnomadVariantsDetailsType.js, and gnomadVariantquery.js would be relevant to the variant page.

variant.js, fetchGnomadVariantsByGene.js, shapeGnomadVariantSummary.js, VariantsInGene.js, variantTableColumns.js would be relevant to the variant table on the gene page.

> also, I named my index file gnomad_exomes_2_1_1 but I still see the original gnomad data. I was under the impression that it gets replaced.

Yes, the export Hail table to Elasticsearch script deletes any existing index.

```python
if es_client.indices.exists(index=index_name):
        es_client.indices.delete(index=index_name)
``` 

Still see original gnomAD data in Elasticsearch? Or in the browser? Is the browser fetching data from your API or the gnomAD API? By default, the start script in projects/gnomad will point the browser at the gnomAD API. To point it at your local API, use `GNOMAD_API_URL=http://localhost:8007/api ./start.sh`.

**Comment by mamtagiri** [comment]
HI!
How does gnomad handle variants with ore than one gene annotation associated with it? Or there is a pipeline to fine map or something before creating the gnomad inout file?
Thanks!!

**Comment by nawatts** [comment]
The gnomAD browser uses [VEP](https://ensembl.org/info/docs/tools/vep/index.html) annotations on variants to associate them with genes.

A variant may have VEP annotations for more than one gene (example: [5-79950723-G-GCCCCCAGC](https://gnomad.broadinstitute.org/variant/5-79950723-G-GCCCCCAGC?dataset=gnomad_r2_1)). All annotations are shown on the variant page. On the region page, only the gene where the variant has the most severe consequence is shown.

**Comment by nawatts** [comment]
The connection refused error suggests that the local API is not running.

To start it, run
```
cd projects/gnomad-api
./start.sh
```

For database connections, you will need to either set `ELASTICSEARCH_URL` and `REDIS_HOST` environment variables or change `DEFAULT_ELASTICSEARCH_URL` and `DEFAULT_REDIS_HOST` in start.sh.

https://github.com/broadinstitute/gnomad-browser/blob/a3c32512711c6f1ddb5f267a6eccc75bec79baac/projects/gnomad-api/start.sh#L11-L14

Also, for Elasticsearch 7, you will probably need to upgrade the Elasticsearch NPM package as well as changing that `apiVersion` argument.
https://github.com/broadinstitute/gnomad-browser/blob/a3c32512711c6f1ddb5f267a6eccc75bec79baac/projects/gnomad-api/package.json#L10

**Comment by mamtagiri** [comment]
> For database connections, you will need to either set `ELASTICSEARCH_URL` and `REDIS_HOST` environment variables or change `DEFAULT_ELASTICSEARCH_URL` and `DEFAULT_REDIS_HOST` in start.sh.
> 
Wouldn't the above still be the same port on local host (URL for elasticsearch). Sorry I still dint understand this part what to change the default URL to.

> https://github.com/broadinstitute/gnomad-browser/blob/a3c32512711c6f1ddb5f267a6eccc75bec79baac/projects/gnomad-api/start.sh#L11-L14
> 
> Also, for Elasticsearch 7, you will probably need to upgrade the Elasticsearch NPM package as well as changing that `apiVersion` argument.
> 
The API version will be the default for the elasticsearch version I have?

**Comment by nawatts** [comment]
If using a local instance of Elasticsearch, that URL should probably be `http://localhost:9200`.

I don't know if the legacy Elasticsearch client gnomAD uses supports Elasticsearch 7. There's a newer Elasticsearch client (on NPM as [@elastic/elasticsearch](https://www.npmjs.com/package/@elastic/elasticsearch) instead of [elasticsearch](https://www.npmjs.com/package/elasticsearch)). For the newer library, https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/introduction.html#_compatibility says
> We recommend you to use the same major version of the client as the Elasticsearch instance that you are using.

**Comment by mamtagiri** [comment]
Ok thanks. Changing elasticsearch to http://localhost:9200 actually fixed it. Thanks!!

Since I only have one dataset (I named it 'gnomad_exomes_2_1_1' just to avoid any errors when replacing the original), do I need to remove the other index for genome or this wouldn't matter?)

Yes, ES 7.6 might not be compatible, I get the following error which could be due the incompatibility.

`{"message":"[index_not_found_exception] no such index [genes], with { resource.type=\"index_or_alias\" & resource.id=\"genes\" & index_uuid=\"_na_\" & index=\"genes\" }","stack_trace":"Error: [index_not_found_exception] no such index [genes], with { resource.type=\"index_or_alias\" & resource.id=\"genes\" & index_uuid=\"_na_\" & index=\"genes\" }\n    at respond (/home/mamta/Test/gnomad-browser/node_modules/elasticsearch/src/lib/transport.js:308:15)\n    at checkRespForFailure (/home/mamta/Test/gnomad-browser/node_modules/elasticsearch/src/lib/transport.js:267:7)\n    at HttpConnector.<anonymous> (/home/mamta/Test/gnomad-browser/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)\n    at IncomingMessage.wrapper (/home/mamta/Test/gnomad-browser/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:328:22)\n    at endReadableNT (_stream_readable.js:1201:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","severity":"WARNING"}`

**Comment by mamtagiri** [comment]
> If using a local instance of Elasticsearch, that URL should probably be `http://localhost:9200`.
> 
> I don't know if the legacy Elasticsearch client gnomAD uses supports Elasticsearch 7. There's a newer Elasticsearch client (on NPM as [@elastic/elasticsearch](https://www.npmjs.com/package/@elastic/elasticsearch) instead of [elasticsearch](https://www.npmjs.com/package/elasticsearch)). For the newer library, https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/introduction.html#_compatibility says
> 
> > We recommend you to use the same major version of the client as the Elasticsearch instance that you are using.

Probably I will have to change my ES version? Should I change to 6.6. Will that be compatible? Or is there a better solution to it?
Thanks!!

**Comment by nawatts** [comment]
> Since I only have one dataset (I named it 'gnomad_exomes_2_1_1' just to avoid any errors when replacing the original), do I need to remove the other index for genome or this wouldn't matter?)

You could remove the code that queries the genome index. Otherwise, you'll probably see some errors.

> Yes, ES 7.6 might not be compatible, I get the following error which could be due the incompatibility.

That error looks like it's attempting to query the "genes" index, which may not exist in your Elasticsearch?

> Probably I will have to change my ES version? Should I change to 6.6. Will that be compatible? Or is there a better solution to it?

It would probably be easier to upgrade the Elasticsearch client library than downgrade Elasticsearch. Assuming the new library provides the same interface as the old, I think the only places to change would be

https://github.com/broadinstitute/gnomad-browser/blob/a3c32512711c6f1ddb5f267a6eccc75bec79baac/projects/gnomad-api/src/server.js#L4

and 

https://github.com/broadinstitute/gnomad-browser/blob/a3c32512711c6f1ddb5f267a6eccc75bec79baac/projects/gnomad-api/src/server.js#L19-L22

**Comment by mamtagiri** [comment]
thanks- the version issue is resolved with @elastic/elasticsearch and changing the way const elastic is defined!

**Comment by mamtagiri** [comment]
I tried to use similar structure as gnomad for the hail table for export (just fewer columns than gnomad)

1. However, for my indexed file I see- 

_"sortedTranscriptConsequences":{"properties":{"gene_id":{"type":"keyword"},"gene_symbol":{"type":"keyword"}}}_

Whereas for the gnomad index I see:
_"sortedTranscriptConsequences":{**"type":"nested"**,"properties":{"amino_acids":{"type":"keyword"},"biotype":{"type":"keyword"},"canonical":{"type":"integer"},"category":{"type":"keyword"},"cdna_end" ..............._

2. My query doesnt seem to find the gene_id/gene_symbol. Could this be due to the nested structure in gnomad but not in my data? 

3. If yes, is there a way I can export to Elasticsearch the same way?
I tried to restructure in hail to match:
_.
.
.
'sortedTranscriptConsequences': struct {
        gene_symbol: str, 
        gene_id: str
}_

Thanks!

**Comment by mamtagiri** [comment]
Hey Nick,

How do I check if the indexed file is even linked in the script.

My GraphiQL throws errors although I have gene_symbol and gene_id both as `sortedTranscriptConsequences":{"type":"nested","properties":{"gene_id":{"type":"keyword"},"gene_symbol":{"type":"keyword"}}}`

**ERROR**
`{
  "errors": [
    {
      "message": "One of \"gene_id\" or \"gene_symbol\" is required"
    }
  ],
  "data": {
    "gene": null
  }
}`

**Comment by nawatts** [comment]
> ERROR
> { "errors": [ { "message": "One of \"gene_id\" or \"gene_symbol\" is required" } ], "data": { "gene": null } }

That error message is unrelated to the Elasticsearch mapping for variants. It means that a GraphQL query for gene information is missing a required argument (either `gene_id` or `gene_symbol`).

https://github.com/broadinstitute/gnomad-browser/blob/a3c32512711c6f1ddb5f267a6eccc75bec79baac/projects/gnomad-api/src/schema/index.js#L49-L67

**Comment by mamtagiri** [comment]
hmm.. I am kind of stuck here. I set up the local connections and the browser gets compiled with no errors. but when I search for a gene it doesn't even give an option (like no autofill) and nothing happens when I type the gene (which I know is in the indexed data).
Not sure how to fix this.

Thanks!

**Comment by nawatts** [comment]
Are there any errors output by the API server? Or in the `errors` field of the response to the search query?

An [earlier comment](https://github.com/broadinstitute/gnomad-browser/issues/567#issuecomment-645605693) suggested that the genes index was not created/populated?

> {"message":"[index_not_found_exception] no such index [genes], with { resource.type=\"index_or_alias\" & resource.id=\"genes\" & index_uuid=\"_na_\" & index=\"genes\" }","stack_trace":"Error: [index_not_found_exception] no such index [genes], with { resource.type=\"index_or_alias\" & resource.id=\"genes\" & index_uuid=\"_na_\" & index=\"genes\" }

**Comment by mamtagiri** [comment]
I fixed this issue. Earlier my json structure was a bit different. I don't see any errors related to this anymore.

However, I see `[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)` although GraphiQL open on localhost 8007.

I was more wondering if the script is querying my database correctly. Can I check for that? is querying on GraphiQL the way to debug here?

**Comment by nawatts** [comment]
> However, I see [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

That error would be from the API server attempting to connect to Redis.
https://github.com/broadinstitute/gnomad-browser/blob/a3c32512711c6f1ddb5f267a6eccc75bec79baac/projects/gnomad-api/src/server.js#L114-L117

**Comment by mamtagiri** [comment]
I didn't set up redis locally. Does this need to be set up too? Can I find more information regarding this?

**Comment by nawatts** [comment]
Redis is used to cache the results of some database queries, such as variants and coverage.

There are some instructions for installing Redis at https://redislabs.com/get-started-with-redis/

Alternatively, the Redis client object:
https://github.com/broadinstitute/gnomad-browser/blob/a3c32512711c6f1ddb5f267a6eccc75bec79baac/projects/gnomad-api/src/server.js#L114-L117

could be replaced with a stub:
```js
const redis = {
  get: () => {},
  set: () => {},
}

**Comment by mamtagiri** [comment]
thanks Nick!

One more question (I think I am almost there!) 
Can it handle missing values in the database? Our annotations has some missingness (missing associated genes, consequence etc).

**Comment by nawatts** [comment]
It depends on the field. Some fields are marked [non-null](https://graphql.org/learn/schema/#lists-and-non-null) in the GraphQL schema. For those fields, a missing/null value will cause GraphQL to return an error.

For example:
https://github.com/broadinstitute/gnomad-browser/blob/a3c32512711c6f1ddb5f267a6eccc75bec79baac/projects/gnomad-api/src/schema/types/variant.js#L43-L48

There also may be cases where the browser code assumes that a value will always be present and a missing/null value will cause a rendering error.

**Comment by mamtagiri** [comment]
I tried to query my data and also subsetted the actual gnomad data to similar fieldnames as the custom file. I was querying for a gene name that I knew was in the file.

`{
  "errors": [
    {
      "message": "An unknown error occurred"
    }
  ],
  "data": {
    "gene": null
  }
}`

The structure of the subsetted gnomad file is 

`"properties":{"alt":{"type":"keyword"},"chrom":{"type":"keyword"},"gene_id":{"type":"keyword"},"gene_symbol":{"type":"keyword"},"pos":{"type":"integer"},"ref":{"type":"keyword"},"rsid":{"type":"keyword"},"sortedTranscriptConsequences":{"type":"nested","properties":{"gene_id":{"type":"keyword"},"gene_symbol":{"type":"keyword"},"transcript_id":{"type":"keyword"}}},"transcript_id":{"type":"keyword"},"variant_id":{"type":"keyword"}}},"settings":{"index":{"codec":"best_compression","mapping":{"total_fields":{"limit":"10000"}},"refresh_interval":"-1","number_of_shards":"1","provided_name":"gnomad_exomes_2_1_1"`

I am not sure if its the api [which is giving me the following error]  issue or if the scripts arent working well.
`events.js:293
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8007
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.listen (/home/mamta/Test/gnomad-browser/node_modules/express/lib/application.js:618:24)
    at Module../src/server.js (/home/mamta/Test/gnomad-browser/projects/gnomad-api/dist/server.js:6206:5)
    at __webpack_require__ (/home/mamta/Test/gnomad-browser/projects/gnomad-api/dist/server.js:20:30)
    at Object.0 (/home/mamta/Test/gnomad-browser/projects/gnomad-api/dist/server.js:6530:18)
    at __webpack_require__ (/home/mamta/Test/gnomad-browser/projects/gnomad-api/dist/server.js:20:30)
    at /home/mamta/Test/gnomad-browser/projects/gnomad-api/dist/server.js:84:18
    at Object.<anonymous> (/home/mamta/Test/gnomad-browser/projects/gnomad-api/dist/server.js:87:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8007
}
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by mamtagiri** [comment]
or maybe that I am missing filename "xpos" in my data. Could that cause problem (I see its used in multiple scripts)

**Comment by nawatts** [comment]
> Error: listen EADDRINUSE: address already in use :::8007

That means your API server can't bind to port 8007 because it is already in use. Do you have another instance of the API server running? Or another application on port 8007?

**Comment by mamtagiri** [comment]
I dont think there is any other application running.

However, I can open localhost:8007/api without even running ./start.sh from gnomad-browser/projects/gnomad-api

**Comment by nawatts** [comment]
It sounds like you have an instance of the API server already running, perhaps in the background. Bringing that process to the foreground or stopping that process and starting a new instance of the server should let you see logged error messages.

**Comment by mamtagiri** [comment]
I kill any running processes:
COMMAND   PID  USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
node    31051 mamta   19u  IPv6 220329906      0t0  TCP *:8007 (LISTEN)

And then when I run .start.sh, it gives me the same error.  Not sure how that happens.

**Comment by mamtagiri** [comment]
I have tried to debug but keep getting this error at the graphql: Any suggestion on what this might be?

"{
  "errors": [
    {
      "message": "index_not_found_exception",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "gene"
      ]
    }
  ],
  "data": {
    "gene": null
  }
}

**Comment by nawatts** [comment]
> "message": "index_not_found_exception"

That looks like Elasticsearch is unable to find one of the indices which it is trying to query. Perhaps `genes`?

**Comment by mamtagiri** [comment]
I do have genenames( used the same structure as gnomad (sortedTranscriptConsequences {gene_symbol.,
<img width="474" alt="Screen Shot 2020-06-26 at 11 28 18 AM" src="https://user-images.githubusercontent.com/44902002/85874255-595ae180-b7a0-11ea-8b83-fac8c5dd4122.png">
gene_id)

Do you believe this could be the API connection to ES issue? or scripts that fetch data from this indexed file?

Thanks!!

**Comment by nawatts** [comment]
It's nothing to do with the format of data in an index. One or more of the indices which the API server is attempting to query does not exist at all. Does your Elasticsearch instance have a `genes` index?

**Comment by mamtagiri** [comment]
I think I must have totally got that wrong. I just have one instance in my elasticsearch database which is basically very similar to what we create with the export to Elasticsearch command "gnomad_exomes_2_1_1"

Do I also need to have indices for the other database locally that gnomad queries from? Is that the case?

**Comment by nawatts** [comment]
The API will expect to find all of the following indices in Elasticsearch:

* `clinvar_variants_grch37`
* `clinvar_variants_grch38`
* `exac_constraint`
* `exac_regional_missense_constraint`
* `exac_variants`
* `exacv1_coverage`
* `genes`
* `gnomad_2_1_1_constraint`
* `gnomad_2_1_mnvs`
* `gnomad_exome_coverage_2_1`
* `gnomad_exomes_2_1_1`
* `gnomad_genome_coverage_2_1`
* `gnomad_genomes_2_1_1`
* `gnomad_r3_coverage`
* `gnomad_r3_variants`
* `gnomad_structural_variants_r2_1`
* `pext_grch37`

Most of them you can probably do without (though some data will be missing from the browser). However, `genes` is necessary for any gene or transcript queries. Before any fields on the gene (for example, variants) can be resolved, [the gene itself must first be resolved](https://github.com/broadinstitute/gnomad-browser/blob/ff5137df16e8df213d9758bdbe7edcbd270e0c31/projects/gnomad-api/src/schema/index.js#L55-L67).

Instructions for populating the `genes` index can be found in [data/docs/gene_models.md](https://github.com/broadinstitute/gnomad-browser/blob/master/data/docs/gene_models.md).

**Comment by mamtagiri** [comment]
Thanks so much! This might be the reason for my error.  I didn't realize I had to have this locally. 
Thanks for the instructions will work on resolving this.

Mamta

**Comment by mamtagiri** [comment]
For the part below, if my data is in a different format, can I still have the annotations fetched based on gnomad_sites (as my data will just be a subset of this). Or do I have fetch annotations based on my custom data sites?
`hailctl dataproc submit data-prep \
   --pyfiles ./data/data_utils \
   ./data/get_canonical_transcripts_from_vep.py \
      gs://gnomad-public/release/2.1.1/ht/exomes/gnomad.exomes.r2.1.1.sites.ht \
      gs://gnomad-public/release/2.1.1/ht/genomes/gnomad.genomes.r2.1.1.sites.ht \
      --output $CANONICAL_TRANSCRIPTS_GRCH37_PATH`

**Comment by nawatts** [comment]
You can still use the gnomAD variants and their VEP annotations for getting canonical transcripts.

**Comment by mamtagiri** [comment]
HI Nick,

Is it possible to download "gene" database from somewhere?
I have been facing hail issues while creating gene_models which I still haven't figured how to resolve (Exception in thread "Executor task launch worker for task 138" java.lang.OutOfMemoryError: Java heap space)

**Comment by nawatts** [comment]
We don't have the genes table available for download.

If running Hail locally, memory can be increased by setting the `PYSPARK_SUBMIT_ARGS` environment variable. For example,
```
PYSPARK_SUBMIT_ARGS="--driver-memory 4g pyspark-shell" python script.py
``` 

https://discuss.hail.is/t/how-do-i-increase-the-memory-or-ram-available-to-the-jvm-when-i-start-hail-through-python/133

**Comment by mamtagiri** [comment]
Will try this - Thanks!. I have also contacted Hail team for help.

**Comment by mamtagiri** [comment]
I create and uploaded the "gene" index. 
However, I get the error: Any suggestions on this? I am assuming the query is giving error but I don't see any error on the start API console.

{
  "errors": [
    {
      "message": "Cannot read property 'hits' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "variant"
      ]
    }
  ],
  "data": {
    "variant": null
  }
}

**Comment by mamtagiri** [comment]
Hi Nick,

I am not using or creating the other induces for now except (genes and gnomad_exomes_2_1_1 ) however my api still throws an error as below. Is there a way I can still get this to work without the other indices? If yes, may I know what other scripts I would need to modify?

{"message":"[index_not_found_exception] no such index [gnomad_2_1_mnvs], with { resource.type=\"index_or_alias\" & resource.id=\"gnomad_2_1_mnvs\" & index_uuid=\"_na_\" & index=\"gnomad_2_1_mnvs\" }","stack_trace":"Error: [index_not_found_exception] no such index [gnomad_2_1_mnvs], with { resource.type=\"index_or_alias\" & resource.id=\"gnomad_2_1_mnvs\" & index_uuid=\"_na_\" & index=\"gnomad_2_1_mnvs\" }\n    at respond (/home/mamta/Test/gnomad-browser/node_modules/elasticsearch/src/lib/transport.js:308:15)\n    at checkRespForFailure (/home/mamta/Test/gnomad-browser/node_modules/elasticsearch/src/lib/transport.js:267:7)\n    at HttpConnector.<anonymous> (/home/mamta/Test/gnomad-browser/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)\n    at IncomingMessage.wrapper (/home/mamta/Test/gnomad-browser/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:328:22)\n    at endReadableNT (_stream_readable.js:1201:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","severity":"WARNING"}
{"message":"[index_not_found_exception] no such index [gnomad_2_1_mnvs], with { resource.type=\"index_or_alias\" & resource.id=\"gnomad_2_1_mnvs\" & index_uuid=\"_na_\" & index=\"gnomad_2_1_mnvs\" }","stack_trace":"Error: [index_not_found_exception] no such index [gnomad_2_1_mnvs], with { resource.type=\"index_or_alias\" & resource.id=\"gnomad_2_1_mnvs\" & index_uuid=\"_na_\" & index=\"gnomad_2_1_mnvs\" }\n    at respond (/home/mamta/Test/gnomad-browser/node_modules/elasticsearch/src/lib/transport.js:308:15)\n    at checkRespForFailure (/home/mamta/Test/gnomad-browser/node_modules/elasticsearch/src/lib/transport.js:267:7)\n    at HttpConnector.<anonymous> (/home/mamta/Test/gnomad-browser/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)\n    at IncomingMessage.wrapper (/home/mamta/Test/gnomad-browser/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:328:22)\n    at endReadableNT (_stream_readable.js:1201:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","severity":"WARNING"}

**Comment by mamtagiri** [comment]
HI Nick,

The data is searchable and the api return expect results on both genes and variants.
 However, the browser does not show any results with a gene name?

Was wondering what I should look at to debug this?

Thanks,
Mamta
